version: '3.8'

services:
    node:
        container_name: organizer-finance-front
        build:
            context: .
        ports:
            -   '3003:3000'
        volumes:
            -   ./:/app
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        networks:
            -   organizer_organizer_network

networks:
    organizer_organizer_network:
        external: true